name: Sync docs with Readme

on:
  push:
    branches:
      - main
      # release branches have the form v1.9.x
      - 'v[0-9].*[0-9].x'


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Set up Python 3.8.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydoc-markdown==4.5.1

      - name: Generate API docs
        run: ./.github/utils/pydoc-markdown.sh

      - name: Get current version
        id: current-version
        shell: bash
        run: echo "::set-output name=minor::$(cat VERSION.txt | cut -d "." -f 1,2)"

      - name: Sync docs with unstable release
        if: github.ref_name == 'main'
        uses: readmeio/rdme@7.2.0
        env:
          README_API_KEY: ${{ secrets.README_API_KEY }}
        with:
          rdme: docs ./docs/_src/api/api/temp --key="$README_API_KEY" --version=${{ steps.current-version.outputs.minor }}-unstable

      - name: Sync docs with current release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: readmeio/rdme@7.2.0
        env:
          README_API_KEY: ${{ secrets.README_API_KEY }}
        with:
          rdme: docs ./docs/_src/api/api/temp --key="$README_API_KEY" --version=${{ steps.current-version.outputs.minor }}-unstable
